name = "padariapanidigrano"
main = "src/index.ts"
compatibility_date = "2025-01-20"

[vars]
ADMIN_EMAIL = "panibolosepaes@gmail.com"

# =========================
# D1 DATABASE
# =========================

[[d1_databases]]
binding = "DB"
database_name = "padariapanidigrano_db"
database_id = "71f46eb9425e46e8bce2cddf478d3850"

# =========================
# KV AUTH
# =========================

[[kv_namespaces]]
binding = "KV_AUTH"
id = "e34aed3246dc49ec962e0f40682f28ee"

# =========================
# KV CACHE
# =========================

[[kv_namespaces]]
binding = "KV_CACHE"
id = "6003ead0b2d94c0dbf29e3c6edbd1244"

# =========================
# R2 FILES
# =========================

[[r2_buckets]]
binding = "R2_FILES"
bucket_name = "padariapanidigrano-midias"