import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Toaster } from "./components/ui/toaster";
import { Toaster as Sonner } from "./components/ui/sonner";
import { TooltipProvider } from "./components/ui/tooltip";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { CartProvider } from "./contexts/CartContext";
import { AuthProvider } from "./contexts/AuthContext";
import Index from "./pages/Index";
import Cardapio from "./pages/Cardapio";
import Auth from "./pages/Auth";
import Contato from "./pages/Contato";
import SobreNos from "./pages/SobreNos";
import Checkout from "./pages/Checkout";
import NotFound from "./pages/NotFound";
import WhatsAppButton from './components/layout/WhatsAppButton';
import Localizacao from "./pages/Localizacao";
import TermosUso from "./pages/TermosUso";
import FAQ from "./pages/FAQ";
import PoliticasPrivacidade from "./pages/PoliticasPrivacidade";
import PainelAdmin from "./pages/PainelAdmin";
import PaniLogin from "./pages/PaniLogin";
import { SpeedInsights } from "@vercel/speed-insights/react";
const queryClient = new QueryClient();
const App = () => (_jsx(QueryClientProvider, { client: queryClient, children: _jsxs(TooltipProvider, { children: [_jsx(Toaster, {}), _jsx(Sonner, {}), _jsx(SpeedInsights, {}), _jsx(BrowserRouter, { children: _jsx(AuthProvider, { children: _jsxs(CartProvider, { children: [_jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Index, {}) }), _jsx(Route, { path: "/cardapio", element: _jsx(Cardapio, {}) }), _jsx(Route, { path: "/auth", element: _jsx(Auth, {}) }), _jsx(Route, { path: "/contato", element: _jsx(Contato, {}) }), _jsx(Route, { path: "/sobrenos", element: _jsx(SobreNos, {}) }), _jsx(Route, { path: "/checkout", element: _jsx(Checkout, {}) }), _jsx(Route, { path: "/localizacao", element: _jsx(Localizacao, {}) }), _jsx(Route, { path: "/termos-uso", element: _jsx(TermosUso, {}) }), _jsx(Route, { path: "/faq", element: _jsx(FAQ, {}) }), _jsx(Route, { path: "/politicas-privacidade", element: _jsx(PoliticasPrivacidade, {}) }), _jsx(Route, { path: "/paineladmin", element: _jsx(PainelAdmin, {}) }), _jsx(Route, { path: "/panilogin", element: _jsx(PaniLogin, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }), _jsx(WhatsAppButton, {})] }) }) })] }) }));
export default App;
